// PHASES - Definições de todas as fases do jogo Meu Amigo Jesus
// 23 fases cobrindo toda a vida de Jesus, da Anunciação à Ascensão

const FASES = [
    {
        id: 'anunciacao', numero: 1, emoji: '👼', titulo: 'A ANUNCIAÇÃO',
        historia: 'O anjo Gabriel apareceu a Maria e disse: "Não tenha medo! Você será a mãe de Jesus, o Filho de Deus!"',
        fala: '{nome}, antes de eu nascer, meu Pai enviou o anjo Gabriel para falar com minha mãe Maria. Ela era jovem e humilde, mas seu coração era cheio de fé. Quando ouviu a mensagem, disse: "Eu sou a serva do Senhor!" Que exemplo de confiança, meu pequeno amigo!',
        instrucao: 'Toque no anjo Gabriel para ouvir a mensagem de Deus!',
        cenario: 'anunciacao', interacao: 'clicar',
        dados: { alvo: 'anjo-gabriel', emoji: '👼' },
        medalha: 'anunciacao',
        versiculo: 'Lucas 1:38 - "Eu sou a serva do Senhor!"',
        licao: 'Maria confiou em Deus. Nós também podemos confiar!',
        oracao: 'Querido Deus, ajuda-me a confiar em Ti como Maria confiou. Amém.',
        som: 'Alegria no céu!',
        imagens: { fundo: null, fundoHistoria: null, mapa: {} }
    },
    {
        id: 'nascimento', numero: 2, emoji: '⭐', titulo: 'JESUS NASCE',
        historia: 'Jesus nasceu em Belém, numa manjedoura, porque não havia lugar na hospedaria. Uma estrela brilhante apareceu no céu!',
        fala: 'Eu nasci em Belém, num lugar bem simples, deitado numa manjedoura. Sabe por quê, {nome}? Porque o verdadeiro tesouro não está no luxo, mas no amor. O mais importante é o coração, meu pequeno!',
        instrucao: 'Toque na estrela para guiar os pastores até Jesus!',
        cenario: 'nascimento', interacao: 'clicar',
        dados: { alvo: 'star-bethlehem', emoji: '⭐' },
        medalha: 'amigo_jesus',
        versiculo: 'Lucas 2:7 - "Ela o enrolou em panos e o colocou numa manjedoura."',
        licao: 'Jesus nasceu humilde. O amor é o maior tesouro!',
        oracao: 'Obrigado, Jesus, por nascer por nós. Ensina-me a ser humilde. Amém.',
        som: 'Brilha, brilha estrelinha!',
        imagens: { fundo: null, fundoHistoria: null, mapa: {} }
    },
    {
        id: 'pastores', numero: 3, emoji: '🐑', titulo: 'OS PASTORES',
        historia: 'Anjos apareceram aos pastores no campo e disseram: "Nasceu o Salvador!" Eles correram para ver Jesus.',
        fala: 'Os pastores foram os primeiros a me visitar, {nome}! Eram pessoas simples, que cuidavam das ovelhas no campo. Mas tinham o coração cheio de amor e fé. Deus sempre escolhe os humildes para receber as maiores alegrias!',
        instrucao: 'Encontre os 3 pastores escondidos no campo!',
        cenario: 'pastores', interacao: 'encontrar',
        dados: { alvos: ['pastor1', 'pastor2', 'pastor3'], total: 3 },
        medalha: 'pastores',
        versiculo: 'Lucas 2:16 - "Foram apressadamente e encontraram Maria, José e o menino."',
        licao: 'Os primeiros a saber foram os humildes. Deus ama todos!',
        oracao: 'Pai, ajuda-me a ter um coração humilde como os pastores. Amém.',
        som: 'Glória a Deus nas alturas!',
        imagens: { fundo: null, fundoHistoria: null, mapa: {} }
    },
    {
        id: 'reismagos', numero: 4, emoji: '👑', titulo: 'OS REIS MAGOS',
        historia: 'Três reis magos seguiram a estrela por muitos dias até encontrar Jesus. Trouxeram ouro, incenso e mirra.',
        fala: 'Três reis sábios viajaram por muitos dias, seguindo uma estrela brilhante no céu, só para me visitar! Eles trouxeram presentes preciosos. Sabe qual é o melhor presente que você pode me dar, {nome}? O seu coração cheio de amor!',
        instrucao: 'Toque nas estrelas na ordem certa para guiar os Reis Magos!',
        cenario: 'reismagos', interacao: 'sequencia',
        dados: { sequencia: ['estrela1', 'estrela2', 'estrela3', 'estrela4'] },
        medalha: 'reismagos',
        versiculo: 'Mateus 2:11 - "Abriram seus tesouros e lhe ofereceram presentes."',
        licao: 'Devemos oferecer nosso coração a Jesus!',
        oracao: 'Jesus, ofereço meu coração para Ti, como os reis magos ofereceram presentes. Amém.',
        som: 'Vamos seguir a estrela!',
        imagens: { fundo: null, fundoHistoria: null, mapa: {} }
    },
    {
        id: 'templosimeao', numero: 5, emoji: '🏛️', titulo: 'SIMEÃO NO TEMPLO',
        historia: 'Quando Jesus foi apresentado no templo, o velho Simeão o recebeu nos braços e disse: "Agora posso descansar, pois vi o Salvador!"',
        fala: 'Havia um velho chamado Simeão, que esperou a vida inteira para ver o Salvador. Quando me tomou em seus braços, seus olhos se encheram de lágrimas de alegria. Ele disse: "Agora posso descansar em paz!" A paciência e a fé são grandes virtudes, meu pequeno {nome}!',
        instrucao: 'Responda: quem reconheceu Jesus no templo?',
        cenario: 'templo', interacao: 'quiz',
        dados: {
            pergunta: 'Quem recebeu Jesus nos braços no templo?',
            opcoes: ['Simeão', 'Um rei', 'Um soldado'],
            correta: 0
        },
        medalha: 'simeao',
        versiculo: 'Lucas 2:30 - "Meus olhos viram a tua salvação!"',
        licao: 'Nunca devemos perder a esperança em Deus!',
        oracao: 'Deus, ensina-me a ter paciência e nunca perder a esperança. Amém.',
        som: 'Agora posso descansar em paz!',
        imagens: { fundo: null, fundoHistoria: null, mapa: {} }
    },
    {
        id: 'templo12', numero: 6, emoji: '📖', titulo: 'JESUS AOS 12 ANOS',
        historia: 'Aos 12 anos, Jesus ficou no templo conversando com os mestres. Todos se admiravam de sua sabedoria!',
        fala: 'Quando eu tinha 12 anos, fiquei no templo conversando com os mestres da lei. Eles ficaram admirados com as minhas palavras! Eu amava estudar sobre meu Pai. Aprender sobre Deus é como plantar uma semente que cresce e dá muitos frutos, {nome}. Você também pode aprender muito sobre o Pai celestial!',
        instrucao: 'Responda: onde Maria e José encontraram Jesus?',
        cenario: 'templo12', interacao: 'quiz',
        dados: {
            pergunta: 'Onde Maria e José encontraram Jesus depois de 3 dias?',
            opcoes: ['No mercado', 'No templo', 'Na praia'],
            correta: 1
        },
        medalha: 'sabedoria',
        versiculo: 'Lucas 2:49 - "Não sabiam que eu devia estar na casa de meu Pai?"',
        licao: 'Jesus amava aprender sobre Deus. Nós também devemos!',
        oracao: 'Jesus, ajuda-me a amar aprender sobre Ti e sobre o Pai. Amém.',
        som: 'Eu amo aprender!',
        imagens: { fundo: null, fundoHistoria: null, mapa: {} }
    },
    {
        id: 'batismo', numero: 7, emoji: '💧', titulo: 'O BATISMO',
        historia: 'João Batista batizou Jesus no rio Jordão. O Espírito Santo desceu como uma pomba e Deus disse: "Este é o meu Filho amado!"',
        fala: 'João me batizou nas águas do rio Jordão. Nesse momento, {nome}, o Espírito Santo desceu como uma pomba e meu Pai disse: "Este é o meu Filho amado!" Foi um momento tão lindo! O batismo é um símbolo de obediência e amor a Deus.',
        instrucao: 'Toque em Jesus para mergulhar no rio Jordão!',
        cenario: 'batismo', interacao: 'clicar',
        dados: { alvo: 'jesus-river', emoji: '🙏' },
        medalha: 'batismo',
        versiculo: 'Mateus 3:17 - "Este é o meu Filho amado em quem me alegro!"',
        licao: 'O batismo mostra nossa obediência a Deus!',
        oracao: 'Pai, quero ser obediente a Ti como Jesus foi no batismo. Amém.',
        som: 'Eis o Cordeiro de Deus!',
        imagens: { fundo: null, fundoHistoria: null, mapa: {} }
    },
    {
        id: 'deserto', numero: 8, emoji: '🪨', titulo: 'A TENTAÇÃO',
        historia: 'No deserto, Jesus ficou 40 dias sem comer. O diabo tentou Jesus, mas Ele escolheu obedecer a Deus sempre!',
        fala: 'No deserto, fiquei 40 dias sem comer. O tentador me ofereceu comida e poder, mas eu escolhi obedecer a meu Pai. A Palavra de Deus é mais forte que qualquer coisa deste mundo, {nome}! Lembre-se: nem só de pão vive o homem, mas de toda palavra de Deus.',
        instrucao: 'Escolha: o que Jesus escolheu — comida ou a Palavra de Deus?',
        cenario: 'deserto', interacao: 'escolha',
        dados: {
            opcaoCerta: { emoji: '📖', texto: 'PALAVRA DE DEUS' },
            opcaoErrada: { emoji: '🍞', texto: 'COMIDA' }
        },
        medalha: 'obediente',
        versiculo: 'Mateus 4:4 - "Não só de pão viverá o homem, mas de toda palavra de Deus."',
        licao: 'Devemos escolher obedecer a Deus sempre!',
        oracao: 'Deus, ajuda-me a escolher a Tua Palavra sempre, mesmo quando é difícil. Amém.',
        som: 'Eu escolho Deus!',
        imagens: { fundo: null, fundoHistoria: null, mapa: {} }
    },
    {
        id: 'discipulos', numero: 9, emoji: '🎣', titulo: 'PESCADORES DE HOMENS',
        historia: 'Jesus chamou pescadores para segui-lo: Pedro, André, Tiago e João. Ele disse: "Vou fazer de vocês pescadores de homens!"',
        fala: 'Caminhando à beira do mar, vi pescadores lançando suas redes. Chamei Pedro, André, Tiago e João. Eles deixaram tudo para me seguir! Saiba que eu também chamo você, {nome}. Você também é meu amigo!',
        instrucao: 'Toque nos 4 pescadores para eles seguirem Jesus!',
        cenario: 'pescadores', interacao: 'clicar-multi',
        dados: { alvos: ['p1', 'p2', 'p3', 'p4'], total: 4 },
        medalha: 'discipulo',
        versiculo: 'Mateus 4:19 - "Sigam-me, e eu os farei pescadores de homens."',
        licao: 'Jesus chama cada um de nós para segui-lo!',
        oracao: 'Jesus, eu quero Te seguir como os discípulos. Mostra o caminho. Amém.',
        som: 'Vamos seguir Jesus!',
        imagens: { fundo: null, fundoHistoria: null, mapa: {} }
    },
    {
        id: 'cana', numero: 10, emoji: '💧', titulo: 'BODAS DE CANÁ',
        historia: 'Numa festa de casamento, a água acabou. Jesus transformou água em vinho! Esse foi seu primeiro milagre!',
        fala: 'Numa festa de casamento em Caná, a bebida acabou. Minha mãe Maria me pediu ajuda. Transformei água em vinho! Foi o meu primeiro milagre. Vês, {nome}? Deus se importa até com as coisas pequenas da nossa vida. Nada é demasiado pequeno para o amor de Deus!',
        instrucao: 'Arraste as jarras de água até Jesus para transformar em vinho!',
        cenario: 'cana', interacao: 'arrastar',
        dados: { alvos: ['jarra1', 'jarra2', 'jarra3'], destino: 'jesus-cana' },
        medalha: 'milagre_cana',
        versiculo: 'João 2:11 - "Revelou assim sua glória, e os discípulos creram nele."',
        licao: 'Jesus cuida até das coisas pequenas da nossa vida!',
        oracao: 'Jesus, obrigado por cuidares de mim e das coisas pequenas da minha vida. Amém.',
        som: 'Jesus faz milagres!',
        imagens: { fundo: null, fundoHistoria: null, mapa: {} }
    },
    {
        id: 'bemaventurancas', numero: 11, emoji: '😊', titulo: 'AS BEM-AVENTURANÇAS',
        historia: 'Jesus subiu o monte e ensinou: "Felizes os humildes, os que choram, os que têm fome de justiça, os misericordiosos!"',
        fala: 'Subi o monte e ensinei uma grande lição: felizes são os humildes, os que têm o coração puro, os que promovem a paz! A verdadeira felicidade não está nas riquezas, mas em amar a Deus e ao próximo. Guarda estas palavras no teu coração, {nome}, meu pequeno!',
        instrucao: 'Complete a frase: "Felizes os ___, porque deles é o Reino de Deus!"',
        cenario: 'monte', interacao: 'completar',
        dados: {
            frase: 'Felizes os ___, porque deles é o Reino de Deus!',
            opcoes: ['humildes', 'ricos', 'fortes'],
            correta: 0
        },
        medalha: 'abençoada',
        versiculo: 'Mateus 5:3 - "Felizes os humildes em espírito, porque deles é o Reino dos céus."',
        licao: 'A verdadeira felicidade vem de ser humilde e amar!',
        oracao: 'Jesus, ajuda-me a ser humilde e a amar a Deus e ao próximo. Amém.',
        som: 'Eu sou feliz com Jesus!',
        imagens: { fundo: null, fundoHistoria: null, mapa: {} }
    },
    {
        id: 'curaciego', numero: 12, emoji: '👁️', titulo: 'JESUS CURA O CEGO',
        historia: 'Jesus colocou lama nos olhos de um cego e ele passou a enxergar! Todos se admiraram com o milagre!',
        fala: 'Encontrei um cego que nunca tinha visto a luz do dia. Com lama e amor, curei seus olhos! Imagina a alegria dele ao ver o mundo pela primeira vez, {nome}! Jesus pode trazer luz para a tua vida também, meu pequeno!',
        instrucao: 'Toque no cego para Jesus fazer o milagre da visão!',
        cenario: 'curaciego', interacao: 'clicar',
        dados: { alvo: 'blind-man', emoji: '🧑‍🦯' },
        medalha: 'milagre',
        versiculo: 'João 9:11 - "Fui, lavei-me e agora vejo!"',
        licao: 'Jesus pode trazer luz para nossa vida!',
        oracao: 'Jesus, traz luz para a minha vida como trouxeste para o cego. Amém.',
        som: 'Agora eu vejo!',
        imagens: { fundo: null, fundoHistoria: null, mapa: {} }
    },
    {
        id: 'paes', numero: 13, emoji: '🍞', titulo: 'MULTIPLICAÇÃO DOS PÃES',
        historia: 'Com apenas 5 pães e 2 peixes, Jesus alimentou mais de 5000 pessoas! E ainda sobrou comida!',
        fala: 'Uma grande multidão tinha fome, mas só havia 5 pães e 2 peixes. Eu dei graças a Deus e todos comeram! E ainda sobrou comida! Vês, {nome}? Quando compartilhamos com amor, Deus multiplica o pouco que temos. Nunca subestimes o que podes oferecer!',
        instrucao: 'Quantos pães e peixes Jesus tinha? Conte e escolha!',
        cenario: 'paes', interacao: 'contar',
        dados: {
            pergunta: 'Quantos pães Jesus tinha para alimentar 5000 pessoas?',
            opcoes: ['5 pães', '50 pães', '500 pães'],
            correta: 0
        },
        medalha: 'compaixao',
        versiculo: 'João 6:11 - "Então Jesus tomou os pães e os distribuiu."',
        licao: 'Quando compartilhamos com amor, Deus multiplica!',
        oracao: 'Deus, ensina-me a compartilhar com amor o que eu tenho. Amém.',
        som: 'Obrigado, Jesus!',
        imagens: { fundo: null, fundoHistoria: null, mapa: {} }
    },
    {
        id: 'aguas', numero: 14, emoji: '🌊', titulo: 'JESUS ANDA SOBRE A ÁGUA',
        historia: 'De noite, os discípulos estavam com medo na tempestade. Jesus veio andando sobre as águas e disse: "Não tenham medo!"',
        fala: 'Os meus discípulos estavam com medo na tempestade, no meio do mar. Eu caminhei sobre as águas até eles e disse: "Coragem! Sou eu. Não tenham medo!" Com Jesus, nunca precisas temer, {nome}, meu pequeno. A fé acalma qualquer tempestade!',
        instrucao: 'Toque em Jesus para Ele caminhar sobre as águas e acalmar a tempestade!',
        cenario: 'aguas', interacao: 'clicar',
        dados: { alvo: 'jesus-walking', emoji: '🙏' },
        medalha: 'fe',
        versiculo: 'Mateus 14:27 - "Tenham coragem! Sou eu. Não tenham medo!"',
        licao: 'Com Jesus, nós não precisamos ter medo!',
        oracao: 'Jesus, ajuda-me a não ter medo. Com Tu ao meu lado, estou em paz. Amém.',
        som: 'Jesus tem poder!',
        imagens: { fundo: null, fundoHistoria: null, mapa: {} }
    },
    {
        id: 'semeador', numero: 15, emoji: '🌱', titulo: 'A PARÁBOLA DO SEMEADOR',
        historia: 'Jesus contou: um semeador jogou sementes. Algumas caíram em boa terra e deram muito fruto!',
        fala: 'Contei uma história sobre um semeador que lançou sementes. Algumas caíram na pedra, outras entre espinhos, mas as que caíram em boa terra cresceram e deram muito fruto! Sê tu como a boa terra, {nome}: ouve a Palavra de Deus e pratica-a com alegria!',
        instrucao: 'Arraste as sementes para a boa terra para elas crescerem!',
        cenario: 'semeador', interacao: 'arrastar',
        dados: { alvos: ['semente1', 'semente2', 'semente3'], destino: 'boa-terra' },
        medalha: 'semeador',
        versiculo: 'Mateus 13:23 - "A semente em boa terra são os que ouvem e compreendem."',
        licao: 'Nós somos a boa terra quando ouvimos e praticamos a Palavra!',
        oracao: 'Jesus, faz do meu coração uma boa terra para a Tua Palavra crescer. Amém.',
        som: 'A Palavra de Deus cresce em mim!',
        imagens: { fundo: null, fundoHistoria: null, mapa: {} }
    },
    {
        id: 'zaqueu', numero: 16, emoji: '🌳', titulo: 'ZAQUEU NA ÁRVORE',
        historia: 'Zaqueu era baixinho e subiu numa árvore para ver Jesus. Jesus olhou e disse: "Zaqueu, hoje vou na sua casa!"',
        fala: 'Zaqueu era um homem baixinho que subiu numa árvore só para me ver passar. Quando olhei para ele, disse: "Zaqueu, desce depressa! Hoje vou ficar na tua casa!" Ele mudou a sua vida naquele dia. Jesus aceita todos, {nome}, mesmo os que erraram. Ele nos dá sempre uma nova chance!',
        instrucao: 'Toque na árvore para Zaqueu descer e receber Jesus!',
        cenario: 'zaqueu', interacao: 'clicar',
        dados: { alvo: 'tree', emoji: '🌳' },
        medalha: 'amigo',
        versiculo: 'Lucas 19:5 - "Zaqueu, desce depressa. Hoje vou ficar na sua casa!"',
        licao: 'Jesus aceita todos, mesmo os que erraram. Ele nos dá uma nova chance!',
        oracao: 'Jesus, obrigado por me aceitar e me dar sempre uma nova chance. Amém.',
        som: 'Jesus vem na minha casa!',
        imagens: { fundo: null, fundoHistoria: null, mapa: {} }
    },
    {
        id: 'bomsamaritano', numero: 17, emoji: '❤️', titulo: 'O BOM SAMARITANO',
        historia: 'Jesus contou: um homem foi ferido na estrada. Um samaritano parou e cuidou dele, enquanto outros passaram adiante.',
        fala: 'Contei a história de um homem ferido na estrada. Um sacerdote passou adiante, mas um samaritano — um estrangeiro — parou, cuidou dele e pagou sua hospedagem. A lição é esta, {nome}: nosso próximo é qualquer pessoa que precisa de ajuda. Vai e faz o mesmo!',
        instrucao: 'Coloque a história em ordem: toque nas cenas na sequência certa!',
        cenario: 'bomsamaritano', interacao: 'sequencia',
        dados: { sequencia: ['cena-ferido', 'cena-sacerdote', 'cena-samaritano', 'cena-cuidado'] },
        medalha: 'samaritano',
        versiculo: 'Lucas 10:37 - "Vai e faz o mesmo."',
        licao: 'Nosso próximo é qualquer pessoa que precisa de ajuda!',
        oracao: 'Deus, ajuda-me a ser bom para todos que precisam de ajuda. Amém.',
        som: 'Vou ajudar meu próximo!',
        imagens: { fundo: null, fundoHistoria: null, mapa: {} }
    },
    {
        id: 'jerusalem', numero: 18, emoji: '🌿', titulo: 'ENTRADA EM JERUSALÉM',
        historia: 'Jesus entrou em Jerusalém montado num jumentinho. As pessoas agitavam ramos e gritavam: "Hosana! O Rei está chegando!"',
        fala: 'Entrei em Jerusalém montado num jumentinho, com humildade. As pessoas agitavam ramos e gritavam: "Hosana! Bendito o que vem em nome do Senhor!" Receberam-me com alegria. Devemos também nós receber Jesus com alegria no coração, {nome}!',
        instrucao: 'Toque nos ramos para agitar e dizer Hosana!',
        cenario: 'jerusalem', interacao: 'clicar-multi',
        dados: { alvos: ['palm1', 'palm2', 'palm3', 'palm4'], total: 4 },
        medalha: 'hosana',
        versiculo: 'Mateus 21:9 - "Hosana ao Filho de Davi! Bendito o que vem em nome do Senhor!"',
        licao: 'Devemos receber Jesus com alegria em nosso coração!',
        oracao: 'Jesus, eu Te recebo com alegria no meu coração. Hosana! Amém.',
        som: 'Hosana! Hosana!',
        imagens: { fundo: null, fundoHistoria: null, mapa: {} }
    },
    {
        id: 'ceia', numero: 19, emoji: '🍞', titulo: 'A ÚLTIMA CEIA',
        historia: 'Na última ceia, Jesus partilhou pão e vinho com seus amigos e disse: "Façam isso em memória de mim."',
        fala: 'Na minha última ceia com os discípulos, partilhei pão e vinho e disse: "Isto é o meu corpo e o meu sangue. Façam isto em memória de mim." Sempre que partilharem o pão, lembrem-se do meu amor por vocês. Eu amo cada um de vocês, {nome}!',
        instrucao: 'Toque no pão e no vinho para partilhar com Jesus!',
        cenario: 'ceia', interacao: 'clicar-multi',
        dados: { alvos: ['last-bread', 'last-wine'], total: 2 },
        medalha: 'ceia',
        versiculo: 'Lucas 22:19 - "Façam isto em memória de mim."',
        licao: 'Jesus quer que nós sempre nos lembremos do seu amor!',
        oracao: 'Jesus, eu sempre me lembrarei do Teu amor por mim. Amém.',
        som: 'Eu me lembro de você, Jesus!',
        imagens: { fundo: null, fundoHistoria: null, mapa: {} }
    },
    {
        id: 'getsemani', numero: 20, emoji: '🌙', titulo: 'JESUS NO GETSÊMANI',
        historia: 'No jardim, Jesus orou com tristeza: "Pai, se for possível, afasta este sofrimento. Mas não seja como eu quero, e sim como Tu queres!"',
        fala: 'No jardim do Getsêmani, orei com o coração pesado: "Pai, se for possível, afasta este sofrimento. Mas não seja como eu quero, e sim como Tu queres." Foi difícil, mas confiei no Pai. Mesmo nas horas mais difíceis, {nome}, podes confiar em Deus. Ele nunca te abandona!',
        instrucao: 'Toque nas gotas de suor para orar com Jesus no jardim!',
        cenario: 'getsemani', interacao: 'orar',
        dados: { alvos: ['gota1', 'gota2', 'gota3', 'gota4', 'gota5'], total: 5 },
        medalha: 'oracao',
        versiculo: 'Lucas 22:42 - "Não seja como eu quero, mas como Tu queres."',
        licao: 'Mesmo nas horas difíceis, podemos confiar em Deus!',
        oracao: 'Pai, nas horas difíceis, ajuda-me a confiar em Ti como Jesus confiou. Amém.',
        som: 'Pai, seja feita a tua vontade!',
        imagens: { fundo: null, fundoHistoria: null, mapa: {} }
    },
    {
        id: 'cruz', numero: 21, emoji: '✝️', titulo: 'O AMOR MAIOR',
        historia: 'Jesus sofreu e morreu na cruz por amor a nós. Ele perdoou todos e nos mostrou o maior amor de todos!',
        fala: 'Eu sofri muito na cruz, mas fiz isso por amor a você, {nome}. Não há amor maior do que dar a vida pelos amigos. Mesmo na cruz, perdoei aqueles que me feriram. O amor é mais forte que qualquer dor. Lembra-te: Jesus te ama mais do que podes imaginar!',
        instrucao: 'Toque no coração para sentir o amor de Jesus por você!',
        cenario: 'cruz', interacao: 'clicar',
        dados: { alvo: 'love-heart', emoji: '💜' },
        medalha: 'amor_maior',
        versiculo: 'João 15:13 - "Ninguém tem maior amor do que dar a vida pelos amigos."',
        licao: 'Jesus nos ama tanto que deu sua vida por nós!',
        oracao: 'Jesus, obrigado por me amar tanto. Eu também Te amo. Amém.',
        som: 'Jesus me ama!',
        imagens: { fundo: null, fundoHistoria: null, mapa: {} }
    },
    {
        id: 'ressurreicao', numero: 22, emoji: '🌅', titulo: 'JESUS RESSUSCITOU',
        historia: 'No terceiro dia, a pedra do túmulo foi rolada e Jesus estava vivo! A morte foi vencida! Jesus vive para sempre!',
        fala: 'No terceiro dia, {nome}, a pedra do túmulo foi removida e eu estava vivo! A morte não conseguiu me segurar! Eu vivo para sempre, meu pequeno! Aleluia! A vida venceu a morte, e eu te ofereço a vida eterna. Alegria, alegria, meu amigo!',
        instrucao: 'Toque na pedra para ver o túmulo vazio e Jesus ressuscitado!',
        cenario: 'ressurreicao', interacao: 'clicar',
        dados: { alvo: 'stone', emoji: '🪨' },
        medalha: 'ressurreicao',
        versiculo: 'Mateus 28:6 - "Ele não está aqui! Ressuscitou, como tinha dito!"',
        licao: 'Jesus venceu a morte! Ele vive e nos dá vida eterna!',
        oracao: 'Jesus ressuscitado, obrigado por me dar a vida eterna. Aleluia! Amém.',
        som: 'Jesus vive! Aleluia!',
        imagens: { fundo: null, fundoHistoria: null, mapa: {} }
    },
    {
        id: 'ascensao', numero: 23, emoji: '☁️', titulo: 'A ASCENSÃO AO CÉU',
        historia: 'Jesus subiu ao céu diante de seus amigos e disse: "Eu estarei com vocês todos os dias! Vão e contem a todos o meu amor!"',
        fala: 'Subi ao céu diante dos meus amigos, mas não os deixei sozinhos. Eu estarei com você todos os dias, {nome}, até o fim dos tempos! Vai e conta a todos sobre o meu amor. Tu és meu amigo para sempre, meu pequeno. Que a paz fique contigo!',
        instrucao: 'Toque em Jesus para vê-lo subir ao céu e receber sua bênção final!',
        cenario: 'ascensao', interacao: 'clicar',
        dados: { alvo: 'jesus-ascend', emoji: '🙏' },
        medalha: 'ascensao',
        versiculo: 'Mateus 28:20 - "Eu estarei com vocês todos os dias, até o fim dos tempos!"',
        licao: 'Jesus está sempre conosco! Devemos contar seu amor a todos!',
        oracao: 'Jesus, obrigado por estar sempre comigo. Ajuda-me a contar o Teu amor a todos. Amém.',
        som: 'Jesus está sempre comigo!',
        imagens: { fundo: null, fundoHistoria: null, mapa: {} }
    },
    {
        id: 'promessa', numero: 24, emoji: '🕊️', titulo: 'A PROMESSA DO CONSOLADOR',
        historia: 'Antes de subir ao céu, Jesus prometeu: "Não fiquem tristes! Eu vou enviar o Espírito Santo, o Consolador. Ele viverá em vocês para sempre!"',
        fala: 'Antes de subir ao céu, prometi aos meus amigos que não os deixaria sozinhos. Enviarei o Espírito Santo, o Consolador, {nome}. Ele será seu Amigo para sempre, vivendo no seu coração! Não fique triste, pois eu estarei com você sempre!',
        instrucao: 'Toque em Jesus para ouvir Sua promessa do Consolador!',
        cenario: 'promessa', interacao: 'clicar',
        dados: { alvo: 'jesus-promessa', emoji: '🕊️' },
        medalha: 'promessa',
        versiculo: 'João 14:16 - "Eu pedirei ao Pai, e Ele dará a vocês outro Consolador, para estar com vocês para sempre."',
        licao: 'Jesus prometeu o Espírito Santo, o Consolador que nunca nos deixa sozinhos!',
        oracao: 'Jesus, obrigado por prometer o Espírito Santo. Ajude-me a confiar na Tua promessa. Amém.',
        som: 'Jesus cumpre suas promessas!',
        imagens: { fundo: null, fundoHistoria: null, mapa: {} }
    },
    {
        id: 'espera', numero: 25, emoji: '🙏', titulo: 'ESPERANDO EM ORAÇÃO',
        historia: 'Os amigos de Jesus voltaram a Jerusalém e ficaram todos juntos, orando e esperando o Consolador que Jesus prometeu. Eles esperaram com fé e alegria!',
        fala: 'Meus amigos voltaram para Jerusalém e ficaram todos juntos, orando e esperando com fé, {nome}. Eles sabiam que eu cumpria as minhas promessas! Você também pode esperar com fé, pois o Consolador vai chegar ao seu coração!',
        instrucao: 'Toque em cada amigo orando para unir todos em oração!',
        cenario: 'espera', interacao: 'clicar-multi',
        dados: { alvos: ['amigo1', 'amigo2', 'amigo3', 'amigo4'], emoji: '🙏' },
        medalha: 'espera',
        versiculo: 'Atos 1:14 - "Todos eles se reuniam sempre em oração, junto com as mulheres."',
        licao: 'Quando esperamos em oração, nossos corações se preparam para receber o Espírito Santo!',
        oracao: 'Querido Deus, ajude-me a orar e esperar com fé, como os amigos de Jesus. Amém.',
        som: 'A oração prepara o coração!' ,
        imagens: { fundo: null, fundoHistoria: null, mapa: {} }
    },
    {
        id: 'pentecostes', numero: 26, emoji: '🔥', titulo: 'PENTECOSTES - O ESPÍRITO DESCE!',
        historia: 'No dia de Pentecostes, veio um som do céu como um vento forte! Apareceram línguas de fogo sobre cada um e todos ficaram cheios do Espírito Santo!',
        fala: 'No dia de Pentecostes, o Espírito Santo desceu como vento e fogo, {nome}! Todos ficaram cheios do Espírito de Deus e começaram a falar das maravilhas de Deus! O Consolador que prometi chegou! Ele é o Espírito de Deus vivendo em você!',
        instrucao: 'Toque em cada língua de fogo para receber o Espírito Santo!',
        cenario: 'pentecostes', interacao: 'clicar-multi',
        dados: { alvos: ['fogo1', 'fogo2', 'fogo3', 'fogo4', 'fogo5'], emoji: '🔥' },
        medalha: 'pentecostes',
        versiculo: 'Atos 2:4 - "Todos ficaram cheios do Espírito Santo e começaram a falar."',
        licao: 'O Espírito Santo desceu em Pentecostes e encheu os corações com o amor de Deus!',
        oracao: 'Espírito Santo, encha o meu coração com o amor de Deus, como em Pentecostes. Amém.',
        som: 'O Espírito Santo desceu!' ,
        imagens: { fundo: null, fundoHistoria: null, mapa: {} }
    },
    {
        id: 'consolador', numero: 27, emoji: '💜', titulo: 'O CONSOLADOR NO CORAÇÃO',
        historia: 'O Espírito Santo é o Consolador que Jesus enviou. Ele vive em nosso coração, nos ensina, nos consola e nos lembra de tudo que Jesus disse!',
        fala: 'O Espírito Santo é o meu Consolador que vive no seu coração, {nome}! Ele ensina você, consola quando você está triste e lembra você das minhas palavras. Você pode falar com Ele a qualquer momento! Ele é o meu Espírito, vivendo em você para sempre!',
        instrucao: 'Toque no coração para receber o Consolador e descobrir Seus frutos!',
        cenario: 'consolador', interacao: 'clicar',
        dados: { alvo: 'coracao-consolador', emoji: '💜' },
        medalha: 'consolador',
        versiculo: 'João 14:26 - "O Consolador, o Espírito Santo, ensinará a vocês todas as coisas."',
        licao: 'O Espírito Santo vive em nosso coração! Ele nos ensina, consola e lembra de Jesus!',
        oracao: 'Espírito Santo, obrigado por viver no meu coração. Ensine-me e console-me sempre. Amém.',
        som: 'O Consolador vive em mim!',
        imagens: { fundo: null, fundoHistoria: null, mapa: {} }
    },
    {
        id: 'frutos', numero: 28, emoji: '🌳', titulo: 'OS FRUTOS DO ESPÍRITO',
        historia: 'Quando o Espírito Santo vive em nós, Ele produz frutos: amor, alegria, paz, paciência, bondade, fidelidade, mansidão e domínio próprio!',
        fala: 'Quando o Espírito Santo vive em você, {nome}, Ele produz frutos lindos: amor, alegria, paz, paciência, bondade, fidelidade, mansidão e domínio próprio! Cada fruto mostra que o meu Espírito está em você. Deixe o Espírito produzir esses frutos na sua vida!',
        instrucao: 'Toque em cada fruto na árvore para descobrir os frutos do Espírito!',
        cenario: 'frutos', interacao: 'clicar-multi',
        dados: { alvos: ['fruto1', 'fruto2', 'fruto3', 'fruto4', 'fruto5', 'fruto6'], emoji: '🌳' },
        medalha: 'frutos',
        versiculo: 'Gálatas 5:22 - "O fruto do Espírito é amor, alegria, paz, paciência, bondade, fidelidade."',
        licao: 'O Espírito Santo produz em nós frutos bonitos: amor, alegria, paz e muito mais!',
        oracao: 'Espírito Santo, produza em mim os Teus frutos: amor, alegria e paz. Amém.',
        som: 'Os frutos do Espírito!',
        imagens: { fundo: null, fundoHistoria: null, mapa: {} }
    }
];

const MEDALHAS = [
    { id: 'anunciacao', nome: 'ANUNCIAÇÃO', emoji: '👼' },
    { id: 'amigo_jesus', nome: 'AMIGO JESUS', emoji: '⭐' },
    { id: 'pastores', nome: 'PASTOR', emoji: '🐑' },
    { id: 'reismagos', nome: 'REI MAGO', emoji: '👑' },
    { id: 'simeao', nome: 'SIMEÃO', emoji: '🏛️' },
    { id: 'sabedoria', nome: 'SABEDORIA', emoji: '📖' },
    { id: 'batismo', nome: 'BATIZADO', emoji: '💧' },
    { id: 'obediente', nome: 'OBEDIENTE', emoji: '🪨' },
    { id: 'discipulo', nome: 'DISCÍPULO', emoji: '🎣' },
    { id: 'milagre_cana', nome: 'MILAGRE', emoji: '🍷' },
    { id: 'abençoada', nome: 'ABENÇOADA', emoji: '😊' },
    { id: 'milagre', nome: 'VISÃO', emoji: '👁️' },
    { id: 'compaixao', nome: 'COMPAIXÃO', emoji: '🍞' },
    { id: 'fe', nome: 'FÉ', emoji: '🌊' },
    { id: 'semeador', nome: 'SEMEADOR', emoji: '🌱' },
    { id: 'amigo', nome: 'AMIGO', emoji: '🌳' },
    { id: 'samaritano', nome: 'BOM SAMARITANO', emoji: '❤️' },
    { id: 'hosana', nome: 'HOSANA', emoji: '🌿' },
    { id: 'ceia', nome: 'CEIA', emoji: '🍞' },
    { id: 'oracao', nome: 'ORAÇÃO', emoji: '🌙' },
    { id: 'amor_maior', nome: 'AMOR MAIOR', emoji: '💜' },
    { id: 'ressurreicao', nome: 'RESSURREIÇÃO', emoji: '🌅' },
    { id: 'ascensao', nome: 'ASCENSÃO', emoji: '☁️' },
    { id: 'promessa', nome: 'PROMESSA', emoji: '🕊️' },
    { id: 'espera', nome: 'ORAÇÃO', emoji: '🙏' },
    { id: 'pentecostes', nome: 'PENTECOSTES', emoji: '🔥' },
    { id: 'consolador', nome: 'CONSOLADOR', emoji: '💜' },
    { id: 'frutos', nome: 'FRUTOS DO ESPÍRITO', emoji: '🌳' },
];
